#!/usr/bin/perl
#!c:/dev/perl510/bin/perl.exe
#
# Article view page
#
# $Id$

use strict;
use lib '../lib';

use CGI;
use File::Basename;

use BabyDiary::Application;

my $item_id;
my $name = basename($0);
my $path = $ENV{PATH_INFO};
$path =~ s{^/}{};

# Post a new comment to an existing article
if ($path eq 'comment_post') {
	$ENV{PATH_INFO} = "/comment_post";
}

elsif ($path eq 'comment_delete') {
	$ENV{PATH_INFO} = "/comment_delete";
}

# Questions-related...
elsif ($path =~ m{^latest/?$}) {
	$ENV{PATH_INFO} = "/questions_latest";
}

elsif ($path =~ m{^id/(\d+)/?}) {
	$ENV{PATH_INFO} = "/$name";
	$ENV{QUERY_STRING} = "id=$1";
}

elsif ($path =~ m{^delete/id/(\d+)$}) {
	$ENV{PATH_INFO} = "/${name}_delete";
	$ENV{QUERY_STRING} = "id=$1";
}

elsif ($path =~ m{^modify/id/(\d+)$}) {
	$ENV{PATH_INFO} = "/${name}_modify";
	$ENV{QUERY_STRING} = "id=$1";
}

elsif ($path eq 'answer/post') {
	$ENV{PATH_INFO} = "/${name}_answer_post";
}

elsif ($path eq 'new') {
	$ENV{PATH_INFO} = "/${name}_new";
}

elsif ($path eq 'post') { 
	$ENV{PATH_INFO} = "/${name}_post";
}

# View an article through slug
else {

	require BabyDiary::File::Slugs;
	my $slug = BabyDiary::File::Slugs->new();
	$item_id = $slug->find_id($path, $name);

	# Redirect to home page if nothing found
	if (! $item_id) {
		print "Location: /\r\n\r\n";
		exit;
	}

	$ENV{PATH_INFO} = "/$name";
	$ENV{QUERY_STRING} = "id=$item_id";
}

# Instance application object
my $app = BabyDiary::Application->new(
    PARAMS => { cfg_file => '../conf/babydiary.conf' }
);

# Gentleman, start your engines!
$app->run();

