#!c:/dev/perl510/bin/perl.exe
#
# Article view page
#
# $Id: home 46 2008-11-08 11:04:04Z Cosimo $

use strict;
use lib '../lib';

use BabyDiary::Application;

# Instance application object
my $app = BabyDiary::Application->new(
    PARAMS => { cfg_file => '../conf/babydiary.conf' }
);

# Gentleman, start your engines!
$app->run();

