#!c:/dev/perl510/bin/perl.exe
#
# Article view page
#
# $Id: home 46 2008-11-08 11:04:04Z Cosimo $

use strict;
use lib '../lib';

use BabyDiary::Application;
use BabyDiary::File::Slugs;

my $path = $ENV{PATH_INFO};
$path =~ s{^/}{};

my $slug = BabyDiary::File::Slugs->new();
my $article_id = $slug->find_id($path, 'article');

# Redirect to home page if nothing found
if (! $article_id) {
	print "Location: /\n";
}

$ENV{PATH_INFO} = "/article";
$ENV{QUERY_STRING} = "id=$article_id";

# Instance application object
my $app = BabyDiary::Application->new(
    PARAMS => { cfg_file => '../conf/babydiary.conf' }
);

# Gentleman, start your engines!
$app->run();

