#!c:/dev/perl510/bin/perl.exe
#
# Everything starts from here.
# This is the main application invocation CGI.
#
# $Id: start,v 1.3 2007/06/05 23:08:36 cosimo Exp $

use strict;
use lib '../lib';

use BabyDiary::Application;

# Instance application object
my $app = BabyDiary::Application->new(
    PARAMS => { cfg_file => '../conf/babydiary.conf' }
);

# Gentleman, start your engines!
$app->run();

