#!c:/dev/perl510/bin/perl.exe
#
# Main articles RSS Feed
#
# $Id: home 46 2008-11-08 11:04:04Z Cosimo $

use strict;
use lib '../lib';
use BabyDiary::Application::RSS;

my $feed = BabyDiary::Application::RSS::articles();

print
    "Content-type: application/rss+xml", "\n\n",
    $feed, "\n";

